# Generated by Django 5.2.7 on 2025-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_designrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_requests/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in-progress', 'Принято в работу'), ('complete', 'Выполнено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
