# Generated by Django 5.2.7 on 2025-11-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_designrequest_image_designrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
