# Generated by Django 5.2.7 on 2025-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_designrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_results/', verbose_name='Изображение дизайна'),
        ),
    ]
