# Generated by Django 5.2.7 on 2025-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_designrequest_admin_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_requests/', verbose_name='Изображение'),
        ),
    ]
